# Generated by Django 6.0.1 on 2026-04-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='allow_donation',
            field=models.BooleanField(default=False),
        ),
    ]
