# Generated by Django 6.0.1 on 2026-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magar_word', models.CharField(max_length=200)),
                ('english_meaning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dictionary Word',
                'verbose_name_plural': 'Dictionary Words',
                'ordering': ['magar_word'],
            },
        ),
    ]
