# Generated by Django 6.0.1 on 2026-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('ANIMALS', 'Animals'), ('BIRDS', 'Birds'), ('FRUITS', 'Fruits'), ('COLORS', 'Colors'), ('GREETINGS', 'Greetings'), ('CITY', 'City'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
